%% Figures for the Paper "Lack of Selection and Limits to Delegation: Firm Dynamics in Developing Countries"

fontname = 'Helvetica';
set(0,'defaultaxesfontname',fontname);
set(0,'defaulttextfontname',fontname);
set(0,'defaultlegendfontname',fontname);

%% --------------------------------------------------------------------------------------
%%---------------------------------------------------------
disp('Figure 4-A')
  f1 = figure;

  a = [1,2,3,4,5]';
  h0 = plot(a,mUS.meanEmpNorm(1:end-1)','LineWidth'   , 2 );
  hold all
  h01 = plot(a,mUS.meanEmpNorm(1:end-1)','LineWidth'   , 2 );
  hold all
  h1 = plot(a,mUSwUStheta_05.meanEmpNorm(1:end-1)','LineWidth'   , 2 );
  hold all
  h11 = plot(a,mUSwUStheta_05.meanEmpNorm(1:end-1)','LineWidth'   , 2 );
  hold all
  h2 = plot(a,mUSwUStheta_2.meanEmpNorm(1:end-1)','LineWidth'    , 2 );
  hold all
  h21 = plot(a,mUSwUStheta_2.meanEmpNorm(1:end-1)','LineWidth'    , 2 );


  set(h0, ...
  'LineStyle'       , '-'           , ...
  'Color'           , [.1 .1 .1]    , ...
  'LineWidth'       , 3             );

  set(h01, ...
  'LineStyle'       , '-'           , ...
  'Color'           , [.1 .1 .1]    , ...
  'LineWidth'       , 3             , ...
  'Marker'          , 'o'           , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.2 .2 .2]    , ...
  'MarkerFaceColor' , [.7 .7 .7]    );

  set(h1, ...
  'LineStyle'       , '--'           , ...
  'Color'           , [47,107,201]./255    , ...
  'LineWidth'       , 3             );

  set(h11, ...
  'LineStyle'       , '--'           , ...
  'Color'           , [47,107,201]./255    , ...
  'LineWidth'       , 3             ,...
  'Marker'          , 'o'           , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [42 96 180]./255    , ...
  'MarkerFaceColor' , [63 121 210]./255    );

  set(h2, ...
  'LineStyle'       , ':'           , ...
  'Color'           , [201,64,47]./255    , ...
  'LineWidth'       , 3       );

  set(h21, ...
  'LineStyle'       , ':'           , ...
  'Color'           , [201,64,47]./255    , ...
  'LineWidth'       , 3             ,...
  'Marker'          , 'o'           , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [180,57,42]./255    , ...
  'MarkerFaceColor' , [210,80,63]./255    );


  hLegend = legend(           ...
    [h0,h1,h2]     , ...
    '$\theta_{US}=0.196$'              , ...
    '$\theta\hspace{3.8mm} = 0.098$'              , ...
    '$\theta\hspace{3.8mm} = 0.391$'              , ...
    'location', 'NorthWest' );
  xlim([0.5,5.5]);
  ylim([0.75,4.0]);
  label = {'0-5','6-10','11-15','16-20','21-25'};
  set(gca, 'XTickLabel',label);
  hXLabel = xlabel('Age');
  hYLabel = ylabel('Mean Employment');
  legend BOXOFF

  set( gca                       , ...
      'FontName'   , 'Helvetica', 'FontSize',19 );
  set([hXLabel, hYLabel]  , ...
      'FontSize'   , 19          );
  set([hLegend]             , ...
      'FontSize'   , 15, 'Interpreter','latex'           );

  set(gca, ...
    'Box'         , 'on'     , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'off'      , ...
    'XGrid'       , 'off'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1.5         );


  set(gcf, 'PaperPositionMode', 'auto', 'PaperOrientation','landscape');
print(f1,'-dpdf',['output' filesep 'figure4A.pdf'])
close all

%-----------------------------------------------------------------------------------------------
disp('Figure 4-B')
  f1 = figure;

  a = [1,2,3,4,5,6]';
  h0 = plot(a,mUS.shareExitin1ByAgeBySizeOneProdAlt(1:6)','LineWidth'   , 2 );
  hold all
  h01 = plot(a,mUS.shareExitin1ByAgeBySizeOneProdAlt(1:6)','LineWidth'   , 2 );
  hold all
  h1 = plot(a,mUSwdelta75.shareExitin1ByAgeBySizeOneProdAlt(1:6)','LineWidth'   , 2 );
  hold all
  h11 = plot(a,mUSwdelta75.shareExitin1ByAgeBySizeOneProdAlt(1:6)','LineWidth'   , 2 );
  hold all
  h2 = plot(a,mUSwdelta1.shareExitin1ByAgeBySizeOneProdAlt(1:6)','LineWidth'   , 2 );
  hold all
  h21 = plot(a,mUSwdelta1.shareExitin1ByAgeBySizeOneProdAlt(1:6)','LineWidth'   , 2 );
  

  set(h0, ...
  'LineStyle'       , '-'           , ...
  'Color'           , [.1 .1 .1]    , ...
  'LineWidth'       , 3            );

  set(h01, ...
  'LineStyle'       , '-'           , ...
  'Color'           , [.1 .1 .1]    , ...
  'LineWidth'       , 3             , ...
  'Marker'          , 'o'           , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.2 .2 .2]    , ...
  'MarkerFaceColor' , [.7 .7 .7]    );


  set(h1, ...
  'LineStyle'       , '--'           , ...
  'Color'           , [47,107,201]./255    , ...
  'LineWidth'       , 3        );

  set(h11, ...
  'LineStyle'       , '--'           , ...
  'Color'           , [47,107,201]./255    , ...
  'LineWidth'       , 3             ,...
  'Marker'          , 'o'           , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [42 96 180]./255    , ...
  'MarkerFaceColor' , [63 121 210]./255    );


  set(h2, ...
  'LineStyle'       , ':'           , ...
  'Color'           , [201,64,47]./255    , ...
  'LineWidth'       , 3    );

  set(h21, ...
  'LineStyle'       , ':'           , ...
  'Color'           , [201,64,47]./255    , ...
  'LineWidth'       , 3             ,...
  'Marker'          , 'o'           , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [180,57,42]./255    , ...
  'MarkerFaceColor' , [210,80,63]./255    );


  hLegend = legend(           ...
    [h0,h1,h2]     , ...
    '$\delta_{US}=0.60$'              , ...
    '$\delta\hspace{3.8mm} = 0.75$'              , ...
    '$\delta\hspace{3.8mm} = 1.00$'              , ...
    'location', 'NorthEast' );
  xlim([0.5,6.5]);
  label = {'0-1','2-3','4-5','6-10','11-15','16-20'};
  set(gca, 'XTickLabel',label);
  hXLabel = xlabel('Age');
  hYLabel = ylabel('Exit Rate');

  legend BOXOFF

  set( gca                       , ...
      'FontName'   , 'Helvetica', 'FontSize',19 );
  set([hXLabel, hYLabel]  , ...
      'FontSize'   , 19          );
  set([hLegend]             , ...
      'FontSize'   , 15, 'Interpreter','latex'           );

  set(gca, ...
    'Box'         , 'on'     , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'off'      , ...
    'XGrid'       , 'off'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1.5         );
  set(gcf, 'PaperPositionMode', 'auto', 'PaperOrientation','landscape');  
print(f1,'-dpdf', ['output' filesep 'figure4B.pdf'])
close all

%----------------------------------------------------------------------------------------

disp('Figure 5')

  f = figure('Position',[100, 100, 740, 450]);
  h1 = bar(1:alg.NN,eqIN.muAll./(sum(eqIN.muAll)),'LineWidth',3);
  ylim([0,.95]);
  l1 = ylabel('Share of Employment');
  hold all
  yyaxis right
  h2 = plot(1:alg.NN,resultAlpha(1,3:end)', 'LineWidth',4, 'Color',[0.9 .3 .3]);
  hold all
  h3 = plot(1:alg.NN,resultAlpha(2,3:end)', 'LineWidth',4, 'Color',[0.9 .3 .3]);

  h1.FaceColor = [.7 .7 .7];
  h1.EdgeColor = [.3 .3 .3];
  ax = gca;
  ax.YAxis(2).Color = [.9 .3 .3];
  ax.YAxis(1).Color = [.3 .3 .3];

  l2 = ylabel('Share of Managers','Rotation',270);
  l2.Position = [8.35483870967744 0.070000067055226 -1];
  t1 = text(5,.094,'$\alpha_{IN}$','Color',[.9 .3 .3],'FontSize',24,'LineWidth',1);
  t2 = text(5,.123,'$\alpha_{US}$','Color',[.9 .3 .3],'FontSize',24,'LineWidth',1);
  set(t1,'Interpreter','latex')
  set(t2,'Interpreter','latex')

  xlim([.5,7.5]);
  xlabel('Firm size (number of products)')

% legend BOXOFF

  set( gca                       , ...
  'FontName'   , 'Helvetica' , ...
  'FontSize'   , 19          );
  % set([hLegend]             , ...
  % 'FontSize'   , 15, 'Interpreter','latex'           );

  set(gca, ...
  'Box'         , 'on'     , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'off'      , ...
  'XGrid'       , 'off'      , ...
  'XColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1.5         );

  set(gcf, 'PaperPositionMode', 'auto', 'PaperOrientation','landscape');
  print(f,'-dpdf',['output' filesep 'figure5.pdf'])
close all

%-------------------------------------------------------------------------------------------

disp('Figure 6')
dataIN = csvread(['moments' filesep 'managerShareBySizeQuantilesDataIN.csv'],1,1);
  f1 = figure;
  a = 1:8;  
  indiaData = plot(a,dataIN(:,1));
  hold all
  indiaModel = plot(a,managerShareModelBySize);

  set(indiaData                             , ...
  'LineStyle'       , '--'           , ...
  'Marker'          , 'o'           , ...
  'Color'           , [.3 .3 .3]    , ...
  'LineWidth'       , 3             , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.2 .2 .2]    , ...
  'MarkerFaceColor' , [.7 .7 .7]    );
  
  set(indiaModel                             , ...
  'LineStyle'       , '-'          , ...
  'Marker'          , 'o'           , ...
  'Color'           , [.8 .2 .2]    , ...
  'LineWidth'       , 3             , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.9 .2 .2]    , ...
  'MarkerFaceColor' , [.9 .7 .7]    );

xlim([0.5,8.5])

  hXLabel = xlabel('Percentile Rank by Employment');
  hYLabel = ylabel('Share of Managers');
  
  label = {'    Full\newlineSample','Top \newline75%','Top \newline50%','Top \newline25%','Top \newline10%','Top \newline5%','Top \newline1%','Top \newline0.1%'};
  set(gca, 'XTickLabel',label)
  

  hLegend = legend(           ...
    [indiaData,indiaModel]     , ...
    'India - Data'             , ...
    'India - Model'             , ...
    'location', 'NorthWest' );
  legend BOXOFF

  set( gca                       , ...
      'FontName'   , 'Helvetica' , ...
      'FontSize'   , 17          );
  set([hLegend]             , ...
      'FontSize'   , 15, 'Interpreter','latex'           );


  set(gca, ...
    'Box'         , 'on'     , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'off'      , ...
    'XGrid'       , 'off'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1.5         );



  set(gcf, 'PaperPositionMode', 'auto');
  % set(gcf,'PaperOrientation','landscape');
print(f1,'-dpdf',['output' filesep 'figure6.pdf'])
close all

%-----------------------------------------------------------------------------------------------------

disp('Figure 7-A')
  f1 = figure;
  a = [1,2,3,4,5,6]';
  
  shareFirmCountUS = [mUS.data.shareFirmCount00_05,mUS.data.shareFirmCount06_10,mUS.data.shareFirmCount11_15,...
                      mUS.data.shareFirmCount16_20,mUS.data.shareFirmCount21_25,mUS.data.shareFirmCount26_]';
  
  shareFirmCountIN = [mIN.data.shareFirmCount00_05,mIN.data.shareFirmCount06_10,mIN.data.shareFirmCount11_15,mIN.data.shareFirmCount16_20...
                     ,mIN.data.shareFirmCount21_25,mIN.data.shareFirmCount26_]';
                     
  usData = plot(a, shareFirmCountUS);
  hold all
  usData1 = plot(a, shareFirmCountUS);
  hold all
  usModel = plot(a, mUS.numFirmAgeAgeBin1'/mUS.numFirmAgeAgeBin1(1));
  hold all
  usModel1 = plot(a, mUS.numFirmAgeAgeBin1'/mUS.numFirmAgeAgeBin1(1));
  hold all
  indiaData = plot(a, shareFirmCountIN);
  hold all
  indiaModel = plot(a, mIN.numFirmAgeAgeBin1'/mIN.numFirmAgeAgeBin1(1));



  set(usData, ...
  'LineStyle'       , '--'           , ...
  'Color'           , [.3 .3 .3]    , ...
  'LineWidth'       , 3            );

  set(usData1, ...
  'LineStyle'       , '--'           , ...
  'Marker'          , 'o'           , ...
  'Color'           , [.3 .3 .3]    , ...
  'LineWidth'       , 3             , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.2 .2 .2]    , ...
  'MarkerFaceColor' , [.7 .7 .7]    );


  set(usModel, ...
  'LineStyle'       , '-'           , ...
  'Color'           , [.1 .1 .1]    , ...
  'LineWidth'       , 3  );


  set(usModel1, ...
  'LineStyle'       , '-'           , ...
  'Marker'          , 'o'           , ...
  'Color'           , [.1 .1 .1]    , ...
  'LineWidth'       , 3             , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.2 .2 .2]    , ...
  'MarkerFaceColor' , [.7 .7 .7]    );


  set(indiaData                             , ...
  'LineStyle'       , '--'          , ...
  'Marker'          , 'o'           , ...
  'Color'           , [.9 .3 .3]    , ...
  'LineWidth'       , 3             , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.9 .2 .2]    , ...
  'MarkerFaceColor' , [.9 .7 .7]    );
  set(indiaModel                             , ...
  'LineStyle'       , '-'          , ...
  'Marker'          , 'o'           , ...
  'Color'           , [.8 .2 .2]    , ...
  'LineWidth'       , 3             , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.9 .2 .2]    , ...
  'MarkerFaceColor' , [.9 .7 .7]    );


  hXLabel = xlabel('Age'              );
  hYLabel = ylabel('Number of Firms'  );

  t1 = text(5.4,1.3,'$\textbf{\textit{US}}$','Color',[.3 .3 .3],'FontSize',19,'LineWidth',1,'Interpreter','latex');
  t2 = text(5.4,0.4,'$\textbf{\textit{India}}$','Color',[.9 .3 .3],'FontSize',19,'LineWidth',1,'Interpreter','latex');

  ylim([0.0,1.4])
  xlim([0.5,6.5])
  label = {'0-5','6-10','11-15','16-20','21-25','26+'};
  set(gca, 'XTickLabel',label)

  hLegend = legend(           ...
  [usData,usModel]     , ...
  'Data'              , ...
  'Model'              , ...
  'location', 'NorthWest' );

  set( gca                       , ...
  'FontName'   , 'Helvetica' , ...
  'FontSize'   , 19          );
  set([hLegend]             , ...
  'FontSize'   , 18, 'Interpreter','latex'           );
  legend BOXOFF

  set(gca, ...
  'Box'         , 'on'     , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'off'      , ...
  'XGrid'       , 'off'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:.2:2, ...
  'LineWidth'   , 1.5         );

  set(gcf, 'PaperPositionMode', 'auto');
print(f1,'-dpdf',['output' filesep 'figure7A.pdf'])
close all


%-----------------------------------------------------------------------------------

disp('Figure 7-B')

  shareEmp1_4FirmUS = [mUS.data.shareEmp1_4FirmWithin00_05,mUS.data.shareEmp1_4FirmWithin06_10,mUS.data.shareEmp1_4FirmWithin11_15,...
                      mUS.data.shareEmp1_4FirmWithin16_20,mUS.data.shareEmp1_4FirmWithin21_25,mUS.data.shareEmp1_4FirmWithin26_]';

  shareEmp1FirmIN = [mIN.data.shareEmp1FirmWithin00_05,mIN.data.shareEmp1FirmWithin06_10,mIN.data.shareEmp1FirmWithin11_15,mIN.data.shareEmp1FirmWithin16_20,mIN.data.shareEmp1FirmWithin21_25,mIN.data.shareEmp1FirmWithin26_]';
                     
  a = [1,2,3,4,5,6]';
  f1 = figure;
  usData    = plot(a,shareEmp1_4FirmUS);
  hold all
  usData1    = plot(a,shareEmp1_4FirmUS);
  hold all
  usModel    = plot(a,mUS.shareOneProdNorm);
  hold all
  usModel1    = plot(a,mUS.shareOneProdNorm);
  hold all
  indiaData = plot(a,shareEmp1FirmIN);
  hold all
  indiaModel = plot(a,mIN.shareOneProdNorm);


  set(usData, ...
  'LineStyle'       , '--'           , ...
  'Color'           , [.3 .3 .3]    , ...
  'LineWidth'       , 3             );


  set(usData1, ...
  'LineStyle'       , '--'           , ...
  'Marker'          , 'o'           , ...
  'Color'           , [.3 .3 .3]    , ...
  'LineWidth'       , 3             , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.2 .2 .2]    , ...
  'MarkerFaceColor' , [.7 .7 .7]    );

  set(usModel, ...
  'LineStyle'       , '-'           , ...
  'Color'           , [.1 .1 .1]    , ...
  'LineWidth'       , 3    );

  set(usModel1, ...
  'LineStyle'       , '-'           , ...
  'Marker'          , 'o'           , ...
  'Color'           , [.1 .1 .1]    , ...
  'LineWidth'       , 3             , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.2 .2 .2]    , ...
  'MarkerFaceColor' , [.7 .7 .7]    );



  set(indiaData                             , ...
  'LineStyle'       , '--'          , ...
  'Marker'          , 'o'           , ...
  'Color'           , [.9 .3 .3]    , ...
  'LineWidth'       , 3             , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.9 .2 .2]    , ...
  'MarkerFaceColor' , [.9 .7 .7]    );
  set(indiaModel                             , ...
  'LineStyle'       , '-'          , ...
  'Marker'          , 'o'           , ...
  'Color'           , [.8 .2 .2]    , ...
  'LineWidth'       , 3             , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.9 .2 .2]    , ...
  'MarkerFaceColor' , [.9 .7 .7]    );


  hXLabel = xlabel('Age'           );
  hYLabel = ylabel('Share of Small Firms');


  t1 = text(5.5,0.49,'$\textbf{\textit{US}}$','Color',[.3 .3 .3],'FontSize',19,'LineWidth',1,'Interpreter','latex');
  t2 = text(5.5,0.88,'$\textbf{\textit{India}}$','Color',[.9 .3 .3],'FontSize',19,'LineWidth',1,'Interpreter','latex');


  ylim([0.1,1.1])
  xlim([0.5,6.5])
  label = {'0-5','6-10','11-15','16-20','21-25','26+'};
  set(gca, 'XTickLabel',label)

  hLegend = legend(           ...
  [usData,usModel]     , ...
  'Data'              , ...
  'Model'              , ...
  'location', 'SouthWest' );
  legend BOXOFF

  set( gca                       , ...
      'FontName'   , 'Helvetica' , ...
      'FontSize'   , 19          );
  set([hLegend]             , ...
      'FontSize'   , 18, 'Interpreter','latex'           );



  set(gca, ...
    'Box'         , 'on'     , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'off'      , ...
    'XGrid'       , 'off'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'YTick'       , 0.2:.2:1.2, ...
    'LineWidth'   , 1.5         );



  set(gcf, 'PaperPositionMode', 'auto');
  print(f1,'-dpdf',['output' filesep 'figure7B.pdf'])
close all
%-------------------------------------------------------------------------------------------

disp('Figure 8')
  data = csvread(['moments' filesep 'productDistData.csv'],1,1);
  a = 1:10;
  f1 = figure;
  usModel    = plot(a,productDistUS);
  hold all
  usModel1    = plot(a,productDistUS);
  hold all
  usData    = plot(a,data(:,2));
  hold all
  usData1    = plot(a,data(:,2));
  hold all
  indiaModel = plot(a,productDistIN);
  hold all
  indiaData = plot(a,data(:,1));
  
  set(usData, ...
  'LineStyle'       , '--'           , ...
  'Color'           , [.3 .3 .3]    , ...
  'LineWidth'       , 3    );

  set(usData1, ...
  'LineStyle'       , '--'           , ...
  'Marker'          , 'o'           , ...
  'Color'           , [.3 .3 .3]    , ...
  'LineWidth'       , 3             , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.2 .2 .2]    , ...
  'MarkerFaceColor' , [.7 .7 .7]    );

  set(usModel, ...
  'LineStyle'       , '-'           , ...
  'Color'           , [.1 .1 .1]./2    , ...
  'LineWidth'       , 3  );

  set(usModel1, ...
  'LineStyle'       , '-'           , ...
  'Marker'          , 'o'           , ...
  'Color'           , [.1 .1 .1]./2    , ...
  'LineWidth'       , 3             , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.2 .2 .2]    , ...
  'MarkerFaceColor' , [.7 .7 .7]    );

  set(indiaData                             , ...
  'LineStyle'       , '--'          , ...
  'Marker'          , 'o'           , ...
  'Color'           , [.9 .3 .3]    , ...
  'LineWidth'       , 3             , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.9 .2 .2]    , ...
  'MarkerFaceColor' , [.9 .7 .7]    );

  set(indiaModel                             , ...
  'LineStyle'       , '-'          , ...
  'Marker'          , 'o'           , ...
  'Color'           , [.8 .2 .2]./1.1    , ...
  'LineWidth'       , 3             , ...
  'MarkerSize'      , 9             , ...
  'MarkerEdgeColor' , [.9 .2 .2]    , ...
  'MarkerFaceColor' , [.9 .7 .7]    );


  hXLabel = xlabel('Number of Product Lines');
  hYLabel = ylabel('Share of Firms');

  xlim([0,11])
  label = {' ','1','2','3','4','5','6','7','8','9','10+',' '};
  set(gca, 'XTickLabel',label)

  t1 = text(3.3,0.15,'$\textbf{\textit{US}}$','Color',[.3 .3 .3],'FontSize',19,'LineWidth',1,'Interpreter','latex');
  t2 = text(1.2,0.85,'$\textbf{\textit{India}}$','Color',[.9 .3 .3],'FontSize',19,'LineWidth',1,'Interpreter','latex');


  hLegend = legend(           ...
    [usData,usModel]     , ...
    'Data'             , ...
    'Model'             , ...
    'location', 'Best' );
  legend BOXOFF

  set( gca                       , ...
      'FontName'   , 'Helvetica' , ...
      'FontSize'   , 19          );
  set([hLegend]             , ...
      'FontSize'   , 18, 'Interpreter','latex'           );



  set(gca, ...
    'Box'         , 'on'     , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'off'      , ...
    'XGrid'       , 'off'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'XTick'       , 0:11,...
    'LineWidth'   , 1.5         );


  set(gcf, 'PaperPositionMode', 'auto');
print(f1,'-dpdf',['output' filesep 'figure8.pdf'])
close all  

%------------------------------------------------------------------------------
disp('Figure 9')
 
  a = 0:29';
  f1 = figure;

  us = plot(a, [mUS.shareHigh((1:30))-linspace(.04,0,30)]','-','Color',[.3 .3 .3],'LineWidth',3);
  hold all
  us1 = line_fewer_markers(a, [mUS.shareHigh((1:30))-linspace(.04,0,30)]',7,'-','Color',[.3 .3 .3],'markersize',9,'linewidth',3, 'MarkerEdgeColor' , [.2 .2 .2],'MarkerFaceColor' , [.7 .7 .7]);
  hold all
  india = plot(a, [mIN.shareHigh((1:30))'],'--','Color',[.9 .3 .3],'LineWidth',3);
  hold all
  india1 = line_fewer_markers(a, [mIN.shareHigh((1:30))'],7,'--','Color',[.9 .3 .3],'markersize',9,'linewidth',3, 'MarkerEdgeColor' , [.9 .2 .2],'MarkerFaceColor' , [.9 .7 .7]);
  hold all
  usIndiaAlpha = plot(a, [mUSwINdelta.shareHigh((1:30))-linspace(.01,0,30)]',':','Color',[.3 .3 .3],'LineWidth',3);
  hold all 
  usIndiaAlpha1 = line_fewer_markers(a, [mUSwINdelta.shareHigh((1:30))-linspace(.01,0,30)]',7,':','Color',[.3 .3 .3],'markersize',9,'linewidth',3, 'MarkerEdgeColor' , [.2 .2 .2],'MarkerFaceColor' , [.7 .7 .7]);

  hXLabel = xlabel('Age'              );
  hYLabel = ylabel('Share of High-Type Firms'  );


  ylim([0.05,1])
  
  hLegend = legend(           ...
    [us,india, usIndiaAlpha]     , ...
    'US'              , ...
    'India',...
    'US w/ $\delta_{IND}$'              , ...
    'location', 'SouthEast' );

  set( gca                       , ...
      'FontName'   , 'Helvetica' , ...
      'FontSize'   , 19          );
  set([hLegend]             , ...
      'FontSize'   , 15, 'Interpreter','latex'           );
  legend BOXOFF

   
  set(gca, ...
    'Box'         , 'on'     , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'off'      , ...
    'XGrid'       , 'off'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'YTick'       , 0.0:0.2:1, ...
    'LineWidth'   , 1.5         );

  set(gcf, 'PaperPositionMode', 'auto');
  print(f1,'-dpdf',['output' filesep 'figure9.pdf'])
close all

%-----------------------------------------------------------------------------------------------------------------------------


disp('Figure 11')
  fid = fopen(['moments' filesep 'ctfpINpwt9.csv']);
  C   = textscan(fid, '%f%f','delimiter',',');
  fclose(fid);

  yearEnd  = 2005;
  yearInit = 1985;
  tfpUS2tfpINPathData  = 1./C{2}((C{1} <= yearEnd)&(C{1} >= yearInit));
  qUS2tfpINPathModel   = qUS2qINPathModel((timePath+1985 >=yearInit)&(timePath+1985 <=yearEnd));
  tfpUS2tfpINPathModel = (eqUS.lProdS/eqIN.lProdS)*(eqUS.M/eqIN.M)*qUS2tfpINPathModel;
  f1 = figure('Position', [100, 100, 740, 450]);
  plot(yearInit:yearEnd, tfpUS2tfpINPathData,'-.','Color',[.9 .3 .3] ,'LineWidth',4);
  hold all
  plot(yearInit:yearEnd, tfpUS2tfpINPathModel,'Color',[.3 .3 .3],'LineWidth',4);
  hLegend = legend('Data','Model');

  hXLabel = xlabel('Year');
  hYLabel = ylabel('$TFP_{US,t}/TFP_{IND,t}$');
  set( gca                       , ...
      'FontName'   , 'Helvetica' , ...
      'FontSize'   , 19          );
  set([hLegend]             , ...
      'FontSize'   , 15, 'Interpreter','latex'           );
  set([hYLabel]             , ...
      'FontSize'   , 19, 'Interpreter','latex'           );


  legend BOXOFF
  set(gca, ...
    'Box'         , 'on'     , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'off'      , ...
    'XGrid'       , 'off'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1.5         );

  set(gcf, 'PaperPositionMode', 'auto', 'PaperOrientation','landscape');
  set(0, 'ScreenPixelsPerInch', 70);
  print(f1,'-dpdf',['output' filesep 'figure11.pdf'])
close all
%--------------------------------------------------------------------------------------

disp('Figure 12')

  lambUS   = mUS.data.shareMan;
  lambMUS  = mIN.data.shareManMigrantUS;
  lambInd  = mIN.data.shareMan;
  lambMInd = mIN.data.shareManMigrantIN;   % point estimate


  a        = 1/pUS.vartheta;
  b        = (pUS.alpha*pUS.muM/(pIN.alpha*pIN.muM))*(lambInd*lambMUS/lambUS)^a;
  x        = linspace(0.015,.15,100);
  y        = b*x.^(-a);
  line     = linspace(1,1,100);
  pointCor = b*lambMInd.^(-a);
  textpointCor = num2str(pointCor,2);

  % error bands from bootstrap
  per5  = 0.0436681;
  per95 = 0.080786;

  range5_95  = linspace(per5,per95,50);

  conf5_95   = b*range5_95.^(-a);
  
  f1 = figure();
  h    = zeros(1,4);
  h(1) = plot(x,y);
  hold all
  h(2) = plot(range5_95,conf5_95);
  hold all;
  h(3) = plot(lambMInd,pointCor);
  hold all
  h(4)  = plot(x, line);

  text(lambMInd+.005,pointCor+.05,textpointCor,'Color','k','FontSize',16,'LineWidth',1);


  set(h(1)                                     , ...
    'LineStyle'       , '-.'                     , ...
    'Color'           , [[.7 .3 .3] ]./1.2 , ...
    'LineWidth'       , 4                       );
  set(h(2)                                     , ...
    'LineStyle'       , '-'                     , ...
    'Color'           , [[.7 .3 .3] ]./1 , ...
    'LineWidth'       , 9                       );
  set(h(3)                                    , ...
    'LineStyle'       , '--'                   , ...
    'Marker'          , 'o'                    , ...
    'Color'           , [.7 .3 .3]             , ...
    'LineWidth'       , 2                      , ...
    'MarkerSize'      , 10                     , ...
    'MarkerFaceColor' , [.3 .3 .3] , ...
    'MarkerEdgeColor' , [.3 .3 .3] );

  set(h(4)                                 , ...
    'LineStyle'       , '-'               , ...
    'Color'           , [211,211,211]./1000, ...
    'LineWidth'       , 2                 );

  leg = legend(h(2),'5-95 Confidence Int.');
  legend BOXOFF
  set(leg,'color','none')
  hXLabel = xlabel('$\chi_{IND}^{M}$','Interpreter','LaTex','FontWeight','bold');
  hYLabel = ylabel('$\mathbf{\frac{\alpha_{US}}{\alpha_{IND}}}\hspace{2mm}$','Interpreter','LaTex','FontWeight','bold','rot',0);

  xlim([0.015,0.15])
  ylim([0.5,3.5])

  set(gca                        , ...
      'FontName'   , 'Helvetica' );
  set(gca                        , ...
      'FontSize'   , 18          );
  set(hYLabel                    , ...
      'FontSize'   , 23          );
  set(hXLabel                    , ...
      'FontSize'   , 23          );


  set(gca, ...
    'Box'          , 'on'       , ...
    'XMinorTick'   , 'off'      , ...
    'YMinorTick'   , 'off'      , ...
    'YGrid'        , 'on'       , ...
    'XGrid'        , 'on'       , ...
    'GridLineStyle', '--'       , ...
    'GridColor'    ,[.6 .6 .6]  , ... 
    'XColor'       , [.3 .3 .3] , ...
    'YColor'       , [.3 .3 .3] , ...
    'YTick'        , 1:.5:7.5   , ...
    'LineWidth'    , 1          );

  print(f1,'-dpdf',['output' filesep 'figure12.pdf'])
close all;
%end
